# Generated by Django 5.1.6 on 2025-02-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoManager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
