# Generated by Django 5.1.6 on 2025-03-15 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="updated_at",
        ),
    ]
