# Generated by Django 5.1.6 on 2025-02-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50, null=True)),
                ("description", models.TextField(null=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("quantity", models.PositiveIntegerField(null=True)),
                ("image", models.ImageField(null=True, upload_to="product_image/")),
            ],
        ),
    ]
